# ----
# Site

title: Spices and Mix
url: "https://spicesandmix.com"
baseurl:
google_analytics_key: UA-112067577-1
newsletter_action: "https://github.us17.list-manage.com/subscribe/post?u=e9fb0f7c099446dafec95bd38&amp;id=db0f3cf127" 
disqus_shortname: spices-and-mix

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/logo.png
description: Spices and Mix Food Blog
author:
  name: Shilpa Singh
  email:  sshilpa1187@gmail.com
  # twitter: # twitter username without the @ symbol
social:
  name: Spices and Mix
  # links:
  #   - https://github.com/CloudCannon/treat-jekyll-template

# -----
# Build

paginate: 10
paginate_path: "/:num/"
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      push_sidebar_down: true
      print_stylesheet: true
      comments: true
      _options:
        content:
          width: 1560
          height: 2000
        featured_image:
          width: 1560
          height: 2000
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "index.html"
    values:
      layout: "default"
      push_sidebar_down: true

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# -----------
# CloudCannon

social_icons:
  - Facebook
  - Instagram
  - YouTube
  - RSS

_options:
  author_image:
    width: 400
    height: 400
